include:
  - ./gateway/docker-compose.yaml
  - ./microservices/auth/docker-compose.yaml
  - ./microservices/user_stats/docker-compose.yaml
  - ./microservices/bins/docker-compose.yaml
  - ./microservices/deposit/docker-compose.yaml

networks:
  eco-point-network:
    driver: bridge
    name: microservices-network
    # ipam:
    #   config:
    #     - subnet: 172.20.0.0/16
