"""make user id unique

Revision ID: 7ec8f8d71299
Revises: b9a626bb7997
Create Date: 2026-02-25 21:24:26.844730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ec8f8d71299"
down_revision: Union[str, Sequence[str], None] = "b9a626bb7997"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_stats", schema=None) as batch_op:
        batch_op.create_unique_constraint("user_id_unique", ["userId"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_stats", schema=None) as batch_op:
        batch_op.drop_constraint("user_id_unique", type_="unique")

    # ### end Alembic commands ###
